<?php

namespace AppBundle\Repository\Entity;

/**
 * SalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalaRepository extends \Doctrine\ORM\EntityRepository
{
}
